#!/bin/sh
# Based on http://james-morris.livejournal.com/11010.html.
#
# Modifications:
# - Changed to use the security table, which was created for SECMARK to
#   avoid conflicts with other users of the mangle table.
# - Added entries for udp traffic for testing udp as well.
# - Specified the interface since the tests are only performed over loopback.
# - Set the port number and context to the values used by the test script and policy.

if [ -f /usr/sbin/iptables-legacy ]; then
    IPTABLES=iptables-legacy
else
    IPTABLES=iptables
fi

if [ -f /usr/sbin/ip6tables-legacy ]; then
    IP6TABLES=ip6tables-legacy
else
    IP6TABLES=ip6tables
fi

# Flush the security table.
$IPTABLES -t security -F

# Create a chain for new connection marking.
$IPTABLES -t security -N NEWCONN

# Accept incoming connections, label SYN packets, and copy labels to connections.
$IPTABLES -t security -A INPUT -i lo -p tcp --dport 65535 -m state --state NEW -j NEWCONN
$IPTABLES -t security -A NEWCONN -j SECMARK --selctx system_u:object_r:test_server_packet_t:s0
$IPTABLES -t security -A NEWCONN -j CONNSECMARK --save
$IPTABLES -t security -A NEWCONN -j ACCEPT

# Common rules which copy connection labels to established and related packets.
$IPTABLES -t security -A INPUT -m state --state ESTABLISHED,RELATED -j CONNSECMARK --restore
$IPTABLES -t security -A OUTPUT -m state --state ESTABLISHED,RELATED -j CONNSECMARK --restore

# Label UDP packets similarly.
$IPTABLES -t security -A INPUT -i lo -p udp --dport 65535 -j SECMARK --selctx system_u:object_r:test_server_packet_t:s0
$IPTABLES -t security -A OUTPUT -o lo -p udp --sport 65535 -j SECMARK --selctx system_u:object_r:test_server_packet_t:s0

##### IPv6 entries
$IP6TABLES -t security -F

# Create a chain for new connection marking.
$IP6TABLES -t security -N NEWCONN

# Accept incoming connections, label SYN packets, and copy labels to connections.
$IP6TABLES -t security -A INPUT -i lo -p tcp --dport 65535 -m state --state NEW -j NEWCONN
$IP6TABLES -t security -A NEWCONN -j SECMARK --selctx system_u:object_r:test_server_packet_t:s0
$IP6TABLES -t security -A NEWCONN -j CONNSECMARK --save
$IP6TABLES -t security -A NEWCONN -j ACCEPT

# Common rules which copy connection labels to established and related packets.
$IP6TABLES -t security -A INPUT -m state --state ESTABLISHED,RELATED -j CONNSECMARK --restore
$IP6TABLES -t security -A OUTPUT -m state --state ESTABLISHED,RELATED -j CONNSECMARK --restore

# Label UDP packets similarly.
$IP6TABLES -t security -A INPUT -i lo -p udp --dport 65535 -j SECMARK --selctx system_u:object_r:test_server_packet_t:s0
$IP6TABLES -t security -A OUTPUT -o lo -p udp --sport 65535 -j SECMARK --selctx system_u:object_r:test_server_packet_t:s0
