#!/bin/sh
# Flush the security table.
if [ -f /usr/sbin/iptables-legacy ]; then
    IPTABLES=iptables-legacy
else
    IPTABLES=iptables
fi

if [ -f /usr/sbin/ip6tables-legacy ]; then
    IP6TABLES=ip6tables-legacy
else
    IP6TABLES=ip6tables
fi

$IPTABLES -t security -F
$IPTABLES -t security -X NEWCONN
$IP6TABLES -t security -F
$IP6TABLES -t security -X NEWCONN
