#!/usr/bin/perl
#
# This test validates the parsing of file_contexts.
#

use Test;

BEGIN { plan tests => 4; }

$basedir = $0;
$basedir =~ s|(.*)/[^/]*|$1|;

$result = system "$basedir/test_open $basedir 2>&1";
ok( $result, 0 );

$result = system "$basedir/test_lookup $basedir 2>&1";
ok( $result, 0 );

$result = system "$basedir/test_open_base $basedir 2>&1";
ok( $result, 0 );

$result = system "$basedir/test_validate $basedir 2>&1";
ok( $result, 0 );

exit;
